-- PRETAG AMIS seed data (generated from reviewed R20 workbooks)
-- Sekyere East is assigned to Sekyere South & Central per Regional Executive ruling.

insert into regions (region_name, region_code) values ('Ashanti','ASH');

insert into zones (id, zone_name, zone_code, region_id, is_active) values
  (1, 'Adansi', 'ADA', 1, true),
  (2, 'Ahafo Ano', 'AHA', 1, true),
  (3, 'Amansie', 'AMA', 1, true),
  (4, 'Asante Akim', 'ASA', 1, true),
  (5, 'Asokore Mampong', 'ASO', 1, true),
  (6, 'Atwima Kwanwoma', 'ATW', 1, true),
  (7, 'Atwima Nwabiagya', 'ATW', 1, true),
  (8, 'Bekwai', 'BEK', 1, true),
  (9, 'Bosome Freho', 'BOS', 1, true),
  (10, 'Bosomtwe', 'BOS', 1, true),
  (11, 'Ejisu', 'EJI', 1, true),
  (12, 'Ejura', 'EJU', 1, true),
  (13, 'Kumasi', 'KUM', 1, true),
  (14, 'Kwabre', 'KWA', 1, true),
  (15, 'Mampong', 'MAM', 1, true),
  (16, 'Offinso', 'OFF', 1, true),
  (17, 'Sekyere Kumawu', 'SEK', 1, true),
  (18, 'Sekyere South & Central', 'SEK', 1, true);

insert into districts (id, district_name, district_code, zone_id, is_active) values
  (1, 'Adansi Asokwa', 'ADAN', 1, true),
  (2, 'Adansi North', 'ADA2', 1, true),
  (3, 'Adansi South', 'ADA3', 1, true),
  (4, 'Afigya Kwabre North', 'AFIG', 14, true),
  (5, 'Afigya Kwabre South', 'AFI2', 14, true),
  (6, 'Agona', 'AGON', 14, true),
  (7, 'Ahafo Ano North', 'AHAF', 2, true),
  (8, 'Ahafo Ano South East', 'AHA2', 2, true),
  (9, 'Ahafo Ano South West', 'AHA3', 2, true),
  (10, 'Akrofuom', 'AKRO', 1, true),
  (11, 'Amansie Central', 'AMAN', 8, true),
  (12, 'Amansie South', 'AMA2', 3, true),
  (13, 'Amansie West', 'AMA3', 3, true),
  (14, 'Asante Akim Central', 'ASAN', 4, true),
  (15, 'Asante Akim North', 'ASA2', 4, true),
  (16, 'Asante Akim South', 'ASA3', 4, true),
  (17, 'Asokore Mampong', 'ASOK', 5, true),
  (18, 'Asokwa Municipal', 'ASO2', 13, true),
  (19, 'Atwima Kwanwoma', 'ATWI', 6, true),
  (20, 'Atwima Mponua', 'ATW2', 7, true),
  (21, 'Atwima Nwabiagya Municipal', 'ATW3', 7, true),
  (22, 'Atwima Nwabiagya North', 'ATW4', 7, true),
  (23, 'Bekwai Municipal', 'BEKW', 8, true),
  (24, 'Bosome Freho', 'BOSO', 9, true),
  (25, 'Bosomtwe', 'BOS2', 10, true),
  (26, 'Ejisu Municipal', 'EJIS', 11, true),
  (27, 'Ejura-Sekyeredumase Municipal', 'EJUR', 12, true),
  (28, 'Juaben Municipal', 'JUAB', 11, true),
  (29, 'Kumasi Metro', 'KUMA', 13, true),
  (30, 'Kwabre East Municipal', 'KWAB', 14, true),
  (31, 'Kwadaso Municipal', 'KWAD', 13, true),
  (32, 'Mampong', 'MAMP', 15, true),
  (33, 'Obuasi East Municipal', 'OBUA', 1, true),
  (34, 'Obuasi Municipal', 'OBU2', 1, true),
  (35, 'Offinso Municipal', 'OFFI', 16, true),
  (36, 'Offinso North', 'OFF2', 16, true),
  (37, 'Oforikrom Municipal', 'OFOR', 13, true),
  (38, 'Old Tafo Municipal', 'OLDT', 13, true),
  (39, 'Sekyere Afram Plains', 'SEKY', 17, true),
  (40, 'Sekyere Central', 'SEK2', 18, true),
  (41, 'Sekyere East', 'SEK3', 11, true),
  (42, 'Sekyere Kumawu', 'SEK4', 17, true),
  (43, 'Sekyere South', 'SEK5', 18, true),
  (44, 'Suame Municipal', 'SUAM', 13, true);

insert into district_aliases (district_id, alias, normalized_alias) values
  (1, 'ADANSI ASOKWA DISTRICT', 'adansi asokwa district'),
  (1, 'Adansi Asokwa', 'adansi asokwa'),
  (2, 'ADANSI NORTH DISTRICT', 'adansi north district'),
  (2, 'Adansi North', 'adansi north'),
  (3, 'ADANSI SOUTH DISTRICT', 'adansi south district'),
  (3, 'Adansi South', 'adansi south'),
  (4, 'AFIGYA KWABRE NORTH', 'afigya kwabre north'),
  (5, 'AFIGYA KWABRE SOUTH', 'afigya kwabre south'),
  (6, 'AGONA', 'agona'),
  (6, 'Agona East', 'agona east'),
  (7, 'Ahafo Ano North', 'ahafo ano north'),
  (7, 'Ahafo Ano North District', 'ahafo ano north district'),
  (7, 'Ahafo Ano North Municipal Assembly', 'ahafo ano north municipal assembly'),
  (8, 'Ahafo Ano South East', 'ahafo ano south east'),
  (8, 'Ahafo Ano South East District', 'ahafo ano south east district'),
  (9, 'Ahafo Ano South West', 'ahafo ano south west'),
  (9, 'Ahafo Ano South West District', 'ahafo ano south west district'),
  (10, 'AKROFUOM DISTRICT', 'akrofuom district'),
  (10, 'Akrofuom', 'akrofuom'),
  (11, 'AMANSIE CENTRAL DISTRICT', 'amansie central district'),
  (11, 'Amansie Central', 'amansie central'),
  (12, 'AMANSIE SOUTH', 'amansie south'),
  (13, 'AMANSIE WEST', 'amansie west'),
  (14, 'ASANTE AKIM CENTRAL', 'asante akim central'),
  (14, 'Asante Akim Central Municipal Assembly', 'asante akim central municipal assembly'),
  (15, 'ASANTE AKIM NORTH', 'asante akim north'),
  (16, 'ASANTE AKIM SOUTH', 'asante akim south'),
  (16, 'Asante Akim South Municipal Assembly', 'asante akim south municipal assembly'),
  (17, 'ASOKORE MAMPONG', 'asokore mampong'),
  (17, 'Asokore Mampong Municipal Assembly', 'asokore mampong municipal assembly'),
  (18, 'ASOKWA MUNICIPAL', 'asokwa municipal'),
  (18, 'Asokwa Municipal Assembly', 'asokwa municipal assembly'),
  (19, 'ATWIMA KWANWOMA', 'atwima kwanwoma'),
  (20, 'ATWIMA MPONUA DISTRICT', 'atwima mponua district'),
  (20, 'Atwima Mponua', 'atwima mponua'),
  (21, 'ATWIMA NWABIAGYA MUNICIPAL', 'atwima nwabiagya municipal'),
  (21, 'Atwima Nwabiagya Municipal Assembly', 'atwima nwabiagya municipal assembly'),
  (22, 'ATWIMA NWABIAGYA NORTH DISTRICT', 'atwima nwabiagya north district'),
  (22, 'Atwima Nwabiagya North', 'atwima nwabiagya north'),
  (23, 'BEKWAI MUNICIPAL', 'bekwai municipal'),
  (23, 'Bekwai Municipal Assembly', 'bekwai municipal assembly'),
  (24, 'BOSOME FREHO', 'bosome freho'),
  (25, 'BOSOMTWE', 'bosomtwe'),
  (26, 'EJISU MUNICIPAL ASSEMBLY', 'ejisu municipal assembly'),
  (26, 'Ejisu Municipal', 'ejisu municipal'),
  (27, 'EJURA-SEKYEREDUMASE', 'ejura sekyeredumase'),
  (27, 'Ejura-Sekyedumase Municipal Assembly', 'ejura sekyedumase municipal assembly'),
  (27, 'Ejura-Sekyeredumase Municipal', 'ejura sekyeredumase municipal'),
  (28, 'JUABEN MUNICIPAL', 'juaben municipal'),
  (28, 'Juaben Municipal Assembly', 'juaben municipal assembly'),
  (29, 'KUMASI METRO', 'kumasi metro'),
  (29, 'Kumasi Metropolitan Assembly', 'kumasi metropolitan assembly'),
  (30, 'KWABRE EAST MUNNICIPAL', 'kwabre east munnicipal'),
  (30, 'Kwabere East Municipal Assembly', 'kwabere east municipal assembly'),
  (30, 'Kwabre East Municipal', 'kwabre east municipal'),
  (30, 'Kwabre East Municipal Assembly', 'kwabre east municipal assembly'),
  (31, 'KWADASO MUNICIPAL', 'kwadaso municipal'),
  (31, 'Kwadaso Municipal Assembly', 'kwadaso municipal assembly'),
  (32, 'MAMPONG', 'mampong'),
  (32, 'Mampong Municipal Assembly', 'mampong municipal assembly'),
  (33, 'OBUASI EAST MUNICIPAL', 'obuasi east municipal'),
  (33, 'Obuasi East', 'obuasi east'),
  (34, 'OBUASI MUNICIPAL', 'obuasi municipal'),
  (34, 'Obuasi Municipal Assembly', 'obuasi municipal assembly'),
  (35, 'OFFINSO MUNICIPAL', 'offinso municipal'),
  (35, 'Offinso Municipal Assembly', 'offinso municipal assembly'),
  (36, 'OFFINSO NORTH', 'offinso north'),
  (37, 'OFORIKROM MUNICIPAL', 'oforikrom municipal'),
  (37, 'Oforikrom Municipal Assembly', 'oforikrom municipal assembly'),
  (38, 'OLD TAFO MUNICIPAL', 'old tafo municipal'),
  (38, 'Old Tafo Municipal Assembly', 'old tafo municipal assembly'),
  (39, 'SEKYERE AFRAM PLAINS', 'sekyere afram plains'),
  (40, 'SEKYERE CENTRAL', 'sekyere central'),
  (41, 'SEKYERE EAST DISTRICT', 'sekyere east district'),
  (41, 'Sekyere East', 'sekyere east'),
  (42, 'SEKYERE KUMAWU', 'sekyere kumawu'),
  (43, 'SEKYERE SOUTH', 'sekyere south'),
  (44, 'SUAME MUNICIPAL', 'suame municipal'),
  (44, 'Suame Municipal Assembly', 'suame municipal assembly');
